#!/bin/bash
yum update -y           
yum install -y httpd        
systemctl start httpd           
systemctl enable httpd          
echo "<h1>Hello, this index.html page from $(hostname -f)</h1>" > /var/www/html/index.html
chmod 644 /var/www/html/index.html
echo "<h1>Hello, this index2.html page from $(hostname -f)</h1>" > /var/www/html/index2.html
chmod 644 /var/www/html/index2.html
systemctl restart httpd         			

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#!/bin/bash     
sudo su     
yum update -y       
yum install httpd -y            
echo "<html><h1> Welcome to Whizlabs Server 1 </h1><html>" > /var/www/html/index.html               
systemctl start httpd       
systemctl enable httpd		

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#!/bin/bash

# Switch to superuser (root) to execute commands that require elevated privileges
sudo su

# Update the system packages and software
yum update -y

# Install Apache HTTP Server (httpd) and PHP on the system
yum install httpd php -y

# Start the Apache HTTP Server service
systemctl start httpd

# Enable the Apache HTTP Server service to start on system boot
systemctl enable httpd

# Change the working directory to /var/www/html/ where web files are usually stored
cd /var/www/html/

# Download the index.html file for the main site from a specified URL
wget https://labtask228.s3.amazonaws.com/index.html

# Create a directory named 'user' to store user-related web files
mkdir user

# Change the working directory to 'user'
cd user

# Download the index.html file for the user section from a specified URL
wget https://labtask228.s3.amazonaws.com/user/index.html		

*************************************************************
#!/bin/bash
sudo su 
yum update -y
yum install httpd -y
systemctl start httpd
systemctl enable httpd
cd /var/www/html/
wget https://labresources.whizlabs.com/92a9ca7235acf4a0ad31e9c76c42b92d/index.html
systemctl restart httpd
********************************************************************************
